version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: domainmod-app
    ports:
      - "80:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    volumes:
      - domainmod-data:/var/www/html
    networks:
      - coolify
    depends_on:
      - db
  db:
    image: mariadb:10.5
    container_name: domainmod-db
    environment:
      - MYSQL_ROOT_PASSWORD=your-root-password
      - MYSQL_DATABASE=domainmod
      - MYSQL_USER=domainmod
      - MYSQL_PASSWORD=your-db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - coolify
volumes:
  domainmod-data:
  db-data:
networks:
  coolify:
    external: true